name: RiversFarms
main: com.rivers.farms.RiversFarms
version: 1.0
api-version: '1.21'
authors: [ "RiverBird" ]
description: Immersive farming with right-click harvest, compost, moisture rules, and a custom watering can.
website: https://github.com/sebasgann

commands:
  farmtrample:
    description: Toggle or manage crop trampling.
    usage: "/farmtrample [player] [on|off]"
    permission: riversfarms.trample.toggle
  wateringcan:
    description: Give a custom Watering Can item.
    usage: "/wateringcan [player]"
    permission: riversfarms.wateringcan.give

permissions:
  riversfarms.trample.toggle:
    description: Toggle your own trampling setting.
    default: true
  riversfarms.trample.admin:
    description: Manage others' trampling settings.
    default: op
  riversfarms.wateringcan.give:
    description: Give Watering Can.
    default: op
